# Calculating Across Rows

How do we calculate row-wise in Pandas like we do in Excel?

<img src="https://sandeepmj.github.io/image-host/oil-v-gold.png">

We need a couple of new concepts to do this calculation:

1. Capture a number from a cell and hold in variable.
2. We `apply()`calculations across columns, row-wise, using using a `lambda expression`.


This is step one in your ability to accomplish tasks that are highly specialized to your beats.

In [1]:
## import library
import pandas as pd

In [2]:
## pull in data
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/oil-v-gold-pandas.csv")
df

         Date  PX_GOLD  PX_OIL
0     1/31/08    922.7   91.75
1     2/29/08    975.0  101.84
2     3/31/08    916.2  101.58
3     4/30/08    865.1  113.46
4     5/30/08    887.3  127.35
..        ...      ...     ...
116   9/29/17   1281.5   51.67
117  10/31/17   1270.5   54.38
118  11/30/17   1273.2   57.40
119  12/29/17   1309.3   60.42
120   1/31/18   1339.0   64.73

[121 rows x 3 columns]

What are the different values for row **TWO** in this formula for `PX_GOLD`:

$$\text{Pct Chg at time } t = \frac{\text{Value at time } t - \text{Value at start time}}{\text{Value at start time}} \times 100$$

Use `.iat` to store a value from a specific cell into a variable:

```dataframe["column_name"].iat[row_index_number]```

In [3]:
## hold gold

df["PX_GOLD"].iat[0]

np.float64(922.7)

Also works:

`dataframe.iat[col_index_number, row_index_number]`

In [4]:
## hold gold col index, row index
gold_baseline = df.iat[0,1]
gold_baseline

np.float64(922.7)

Place the value for the starting oil price in a variable called `oil_baseline`

In [5]:
## oil_baseline
oil_baseline = df.iat[0,2]
oil_baseline

np.float64(91.75)

# `lambda expressions`

We're going to just write one first and then break it down:

In [6]:
## create a new column that holds the zero index for gold
df["gold_zero_index"] = df["PX_GOLD"].apply(lambda x: (x-gold_baseline)/gold_baseline * 100)

In [7]:
## call df
df

         Date  PX_GOLD  PX_OIL  gold_zero_index
0     1/31/08    922.7   91.75         0.000000
1     2/29/08    975.0  101.84         5.668148
2     3/31/08    916.2  101.58        -0.704454
3     4/30/08    865.1  113.46        -6.242549
4     5/30/08    887.3  127.35        -3.836567
..        ...      ...     ...              ...
116   9/29/17   1281.5   51.67        38.885878
117  10/31/17   1270.5   54.38        37.693725
118  11/30/17   1273.2   57.40        37.986344
119  12/29/17   1309.3   60.42        41.898775
120   1/31/18   1339.0   64.73        45.117590

[121 rows x 4 columns]

## What  `x` stand for:

- In Pandas, we `apply()` lambda expressions to columns.
-  `.apply()`  works element-wise on each value in the `PX_GOLD` column, one at a time.
- `x` is a single value representing a cell in the column `PX_GOLD`
- The ```lambda x:``` processes each row of a dataframe, one row at a time.
-  The `lambda expression` takes each individual number `x` from `PX_GOLD` and runs the indexing formula on it.

Think of it as: "call each value in `PX_GOLD` as `x`, and do this math to using `x` in the formula."

## create a new column that holds the zero index for oil

In [8]:
## create a new column that holds the zero index for oil

df["oil_zero_index"] = df["PX_OIL"].apply(lambda x: (x-oil_baseline)/oil_baseline * 100)
df

         Date  PX_GOLD  PX_OIL  gold_zero_index  oil_zero_index
0     1/31/08    922.7   91.75         0.000000        0.000000
1     2/29/08    975.0  101.84         5.668148       10.997275
2     3/31/08    916.2  101.58        -0.704454       10.713896
3     4/30/08    865.1  113.46        -6.242549       23.662125
4     5/30/08    887.3  127.35        -3.836567       38.801090
..        ...      ...     ...              ...             ...
116   9/29/17   1281.5   51.67        38.885878      -43.683924
117  10/31/17   1270.5   54.38        37.693725      -40.730245
118  11/30/17   1273.2   57.40        37.986344      -37.438692
119  12/29/17   1309.3   60.42        41.898775      -34.147139
120   1/31/18   1339.0   64.73        45.117590      -29.449591

[121 rows x 5 columns]

### 100-indexing

Create cells below to add columns for both oil and gold for 100-indexing.

Reminder, the formula for 100-indexing:

$$\text{Index} = \left(\frac{\text{value at time } t}{\text{value at start}}\right) \times 100$$

In [9]:
## gold 100
df["gold_100_index"] = df["PX_GOLD"].apply(lambda x: round(x/gold_baseline * 100, 1))
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2
...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1

In [10]:
## oil 100
df["oil_100_index"] = df["PX_OIL"].apply(lambda x: (x)/oil_baseline * 100)
df

,Date,PX_GOLD,PX_OIL,gold_zero_index,oil_zero_index,gold_100_index,oil_100_index
0,1/31/08,922.7,91.75,0.000000,0.000000,100.0,100.000000
1,2/29/08,975.0,101.84,5.668148,10.997275,105.7,110.997275
2,3/31/08,916.2,101.58,-0.704454,10.713896,99.3,110.713896
3,4/30/08,865.1,113.46,-6.242549,23.662125,93.8,123.662125
4,5/30/08,887.3,127.35,-3.836567,38.801090,96.2,138.801090
...,...,...,...,...,...,...,...
116,9/29/17,1281.5,51.67,38.885878,-43.683924,138.9,56.316076
117,10/31/17,1270.5,54.38,37.693725,-40.730245,137.7,59.269755
118,11/30/17,1273.2,57.40,37.986344,-37.438692,138.0,62.561308
119,12/29/17,1309.3,60.42,41.898775,-34.147139,141.9,65.852861
120,1/31/18,1339.0,64.73,45.117590,-29.449591,145.1,70.550409

# Homework

<a href="https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv">This dataset</a> shows the price of a standard cable subscription and the U.S. median income annually between 1995-2023.

Has median income kept pace with the price of a cable subscription?

Round all numbers to 1 decimal place

In [15]:
## read file
df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv")
df.head()

   year  avg_cable_bill  median_household_income
0  1995           22.35                    35249
1  1996           23.28                    36689
2  1997           26.31                    38229
3  1998           27.88                    40148
4  1999           28.94                    41994

In [19]:
## get info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     29 non-null     int64
 1   avg_cable_bill           29 non-null     float64
 2   median_household_income  29 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 828.0 bytes

### Index cable billl

In [21]:
## cable_baseline
cable_baseline = df["avg_cable_bill"].iat[0]
cable_baseline

np.float64(22.35)

In [25]:
## cable bill index
df["cable_index"] = (
    df["avg_cable_bill"]
    .apply(lambda x: x/cable_baseline * 100)
    .round(1)
)

df.head()

   year  avg_cable_bill  median_household_income  cable_index
0  1995           22.35                    35249        100.0
1  1996           23.28                    36689        104.2
2  1997           26.31                    38229        117.7
3  1998           27.88                    40148        124.7
4  1999           28.94                    41994        129.5

### Index median income

In [27]:
## income_baseline
income_baseline = (
    df["median_household_income"].iat[0]
)

income_baseline

np.int64(35249)

In [28]:
## median income index
df["median_income_index"] = (
    df["median_household_income"]
    .apply(lambda x: x/income_baseline * 100)
    .round(1)
)

df.head()

,year,avg_cable_bill,median_household_income,cable_index,median_income_index
0,1995,22.35,35249,100.0,100.0
1,1996,23.28,36689,104.2,104.1
2,1997,26.31,38229,117.7,108.5
3,1998,27.88,40148,124.7,113.9
4,1999,28.94,41994,129.5,119.1

In [29]:
## analysis
df

,year,avg_cable_bill,median_household_income,cable_index,median_income_index
0,1995,22.35,35249,100.0,100.0
1,1996,23.28,36689,104.2,104.1
2,1997,26.31,38229,117.7,108.5
3,1998,27.88,40148,124.7,113.9
4,1999,28.94,41994,129.5,119.1
5,2000,31.22,42349,139.7,120.1
6,2001,33.75,42710,151.0,121.2
7,2002,36.47,43057,163.2,122.2
8,2003,38.95,43564,174.3,123.6
9,2004,41.04,44684,183.6,126.8
10,2005,43.04,46242,192.6,131.2
11,2006,43.26,48451,193.6,137.5
12,2007,47.27,50740,211.5,143.9
13,2008,49.65,52029,222.1,147.6
14,2009,52.37,50221,234.3,142.5
15,2010,54.44,50046,243.6,142.0
16,2011,57.46,50502,257.1,143.3
17,2012,61.63,51371,275.7,145.7
18,2013,69.18,52250,309.5,148.2
19,2014,71.45,53657,319.7,152.2
20,2015,78.42,55775,350.9,158.2
21,2016,150.98,57617,675.5,163.5
22,2017,168.49,61372,753.9,174.1
23,2018,199.99,64324,894.8,182.5
24,2019,210.84,69560,943.4,197.3
25,2020,217.42,67521,972.8,191.6
26,2021,231.10,70784,1034.0,200.8
27,2022,251.48,74580,1125.2,211.6
28,2023,291.81,75143,1305.6,213.2

According to the indexed values, cable prices have rocketed past median household income. The average cable bill in 2023 is 13 times the amount in 1995, while the median household income is only about double the amount across that same span.